### ISSUE TITLE
PLZ update localization in simp-chinese

### ISSUE THREAD

**Issue by YakoseKumin** [Lithane97/Divine-Intervention-Base#1]
Hello, I am the person who has completed the localization of this modifier in **Simplified Chinese**.
And I can guarantee that at least 99.99% of the content has appropriate localized translations.
**Can you add it to the codebase** so that more Chinese players can discover and download this mod?
I found that I couldn't upload an YAML file, so I had to add a link here↓
[https://github.com/YakoseKumin/Localization](url)

_Thanks for your help. I hope I didn't disturb you.
Wishing you a pleasant work and life._

**Comment by Lithane97** [comment]
Thank you! I made a couple of minor alterations and am uploading it now.

**Comment by Lithane97** [comment]
Thank you! I made a couple of minor alterations and am uploading it now.
