### ISSUE TITLE
Mod not enabling after install, possible file path issue?

### ISSUE THREAD

**Issue by teun135** [Lithane97/Divine-Intervention-Base#3]
Hello and thank you for your work on this mod!

I know this isn't really an issue on the mod's end most likely, but as I manually installed this mod (my game version is through Microsoft's PC Game Pass rather than Steam) I am having issues getting it to work. Here is the error log message I am getting:

[14:30:14][lexer.cpp:634]: Location: mod/Divine Intervention.mod(7): Backslash followed by neither quote nor backslash, if you meant to write a single backslash, write two backslashes.

I followed the instructions in the "readme" explicitly, but it still seems to be failing to work. I edited the "Divine Intervention.mod" file and copy-pasted the filepath directly from windows explorer (path="C:\Users\Teun\Documents\Paradox Interactive\Crusader Kings III\mod\Divine-Intervention-Base-master"). 

I guess my question is, should there be a specific file structure? Is this an issue with naming conventions? Do I need to leave the descriptor.mod file alone, or should I remove it from the mod file? Any help would be appreciated!

**Comment by Lithane97** [comment]
So, with windows store it's a bit more complicated to install a mod. It will take some more work on your end. Here is a link to the page where you can get information on that. https://ck3.paradoxwikis.com/Modding#Installing_mods_manually 
About halfway down that page is a header titled Extracting files From Microsoft Store version, with the specific instructions relevant to you.
