### ISSUE TITLE
Court position are gods!!

### ISSUE THREAD

**Issue by Buoya49** [Lithane97/Divine-Intervention-Base#4]
The mod was great in the past you Added Cultural Editor in the new version! Great.. But recently in this last version the only thing that bothers me is that the courtiers for court positions are Godlike and it is really bad!! I mean I'm not using this great mod to cheat but to have a more diverse Role playing campaign! So please adjust that and thank you for the mod

**Comment by Buoya49** [comment]
![Screenshot 2023-11-28 155856](https://github.com/Lithane97/Divine-Intervention-Base/assets/125687599/a83f4650-4ef6-4add-9aa5-b81af26d4e50)

here's an example.. Even whit the No trait option is checked it still spawned whit buffs stats.. I'm not complaining at all as I said I love this mod.. I just find this problem a little bit annoying especially cause there's an option to spawn a 100 trait courtier

**Comment by Lithane97** [comment]
The thing with those court positions is, I just looked at what all the possible traits / stats that give aptitude are, and gave the courtier those traits, to make them perfect for the job. 

I could remove the base stat increases, but I feel like the whole point in spawning a character that way for one of those positions is for the character to be perfect for the job. Even with the base stat reduction, it'll still probably have around 25 for example learning, from all the traits.

My question for you is,  what would you make the stats for these characters? You want 10 base stats across the board, then add all the traits?

**Comment by Buoya49** [comment]
I mean things were smooth at previous versions of your mod. I'd court potential hires, and if their stats didn't quite cut it, I'd just tweak them to my liking. But here's the thing, court jobs in CK3 are all about NPC stats. Take, for instance, wanting a champion, power and Marshal skills are non-negotiable. Now, what's intriguing is that NPCs come pre-loaded with great traits though, all the stats I think are off the charts. So, if one of these NPCs starts disliking me in-game, they're not just sipping tea, they're plotting my character's demise. Especially if they're, say, my court phys or a buddy bodyguard. Sure, I could cheat my way out, maxing their opinion with the mod or making them my BFF, but that's not my style. I use the mod as I say for RP kicks, fixing up the wonky courtiers system in the game and really I love it..

Here's the snag, the spawn with top-tier stats for every skill. How about a bit of randomness, like 20 in the must-haves and some wildcard numbers in the rest? That'd be ideal. Editing used to be a breeze, but now it's like wrangling 50 edits just to tweak 15 or 20. I'm knee-deep in NPC edits instead of forging connections whit them and enjoying the game..
Thank you for your replies and time dho I'm sorry if my replied before wre a little bit short but I was working.. Thank you gain

**Comment by Lithane97** [comment]
I am significantly reducing the base stats of the spawned courtiers / court positions. Should be closer to what you are expecting.
