### ISSUE TITLE
Errors in Log

### ISSUE THREAD

**Issue by Jayshua83** [Lithane97/Divine-Intervention-Base#7]
[03:38:12][E][virtualfilesystem.cpp:449]: Could not find texture due to 'VFSOpen Error: gfx/interface/icons/DI_county_conquest.dds not found'
[03:38:12][E][virtualfilesystem.cpp:449]: Could not find texture due to 'VFSOpen Error: gfx/interface/icons/DI_spouse.dds not found'
[03:39:20][E][static_modifier.cpp:171]: Modifier 'DI_test_modifier' was not used by the script or code but exists in the database, this is a waste

**Comment by Lithane97** [comment]
Thanks for posting these; I know about these specific ones. The DI_test_modifier is just a test modifier that could be removed. The other two are icons that I need to add in. 

If you want to help some more, go into the character editor traits menu, specifically the tracked tab, and try adding max xp to each trait track. If one or more of them is not working, posting the error log would be helpful!

**Comment by Jayshua83** [comment]
The only 3 that didn't work were Charioteering? (Gray, Green, Blue) 

Posting logs of some things that are DI related as well!

[debug.log](https://github.com/user-attachments/files/17194909/debug.log)
[error.log](https://github.com/user-attachments/files/17194911/error.log)
[message.log](https://github.com/user-attachments/files/17194912/message.log)

**Comment by Lithane97** [comment]
All right, they all work then; you could only get one charioteering to work because each is a separate trait that is opposite of the other 3, so you can only have one of the color traits at a time. If you right-click the icon of the one you could get, it should remove that trait, allowing you to add one of the other ones ;)
